# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-23 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ariados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='type',
            field=models.CharField(choices=[('LIKE', 'LIKE'), ('DISLIKE', 'DISLIKE')], default='LIKE', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='friendrequest',
            unique_together=set([('trainer_from', 'trainer_to')]),
        ),
        migrations.AlterUniqueTogether(
            name='isfriendof',
            unique_together=set([('trainer1', 'trainer2')]),
        ),
    ]
