# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-08-02 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ariados', '0003_auto_20180723_1759'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'managed': True, 'ordering': ('days', 'title')},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'managed': True, 'ordering': ('last_update', 'title')},
        ),
        migrations.RemoveField(
            model_name='event',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='location',
        ),
        migrations.RemoveField(
            model_name='event',
            name='start_date',
        ),
        migrations.AddField(
            model_name='event',
            name='days',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(default='', max_length=252),
        ),
    ]
